### ISSUE TITLE
Dont work on Debian 12

### ISSUE THREAD

**Issue by solisinvictum** [LizardByte/Sunshine#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

This Issue still exists: https://github.com/LizardByte/Sunshine/issues/185

How to reproduce: 

Install Debian 12
Install sunshine https://github.com/LizardByte/Sunshine/releases/download/v0.20.0/sunshine-debian-bullseye-amd64.deb
Start sunshine: # sunshine

Exact same Errors like in linked issue.

### Host Operating System

Linux

### Operating System Version

Debian 12

### Architecture

64 bit

### Sunshine commit or version

latest

### Package

Linux - deb

### GPU Type

none (software encoding)

### GPU Model

123

### GPU Driver/Mesa Version

123

### Config

```Shell
123
```

### Relevant log output

```shell
123
```

**Comment by Danny3** [comment]
BTW, why isn't this project available in Debian's repository too?

So we can install it faster, easier and with less problems.

**Comment by ReenigneArcher** [comment]
> BTW, why isn't this project available in Debian's repository too?

Ask Debian maintainers

**Comment by Danny3** [comment]
> Ask Debian maintainers

What do you mean?

Have the developers or any other members of this project filled an ITP (Intent to Package)?

Like explained here:

https://wiki.debian.org/ITP

And like how the OpenSnitch developer did:

https://github.com/evilsocket/opensnitch/issues/798#issuecomment-1382183103

And like how the KDiskMark developer did also:

https://github.com/JonMagon/KDiskMark/issues/110#issuecomment-1356719906

Debian, AFAIK is a community led / run distro, so they probably don't have the knowledge and resources to package any available project, but if somebody from a project steps up and files that ITP and volunteers to build it, I think the chances increases.

Maybe volunteering to build it is not mandatory, but a request at least must be made.

I don't think Debian maintainers are aware about every project on Github or somewhere else.

**Comment by ReenigneArcher** [comment]
> On the other hand, I don't know how often is that the upstream is also the maintainer of the Debian package, but (as of today,) I'd like to focus on developing the app.

Basically, I agree with this sentiment. We make the packages available for everyone on GitHub, and they can be installed with 2 simple commands.

Also, there's no way I'm advocating for putting this into Debian until the project is much more stable and reliable. At this point we don't even have unit testing.

**Comment by Danny3** [comment]
> Basically, I agree with this sentiment. We make the packages available for everyone on GitHub, and they can be installed with 2 simple commands.

For Debian I see in the installation guide that this should be command to install it:
sudo apt install -f ./sunshine-{ubuntu-version}.deb
Even though that's a bit wrong / misleading / outdated, as I see that this project has packages to download for Debian too, not only for Ubuntu.

Anyway, what should be the other command?
And BTW, what's with the "-f" argument, what does that do and why is it needed for this project?
As I always install .deb packages only with:
sudo apt install ./package-name
Or:
sudo dpkg -i ./package-name

>Also, there's no way I'm advocating for putting this into Debian until the project is much more stable and reliable. At this point we don't even have unit testing.

I understand!

I was just thinking for myself, that after each time I install / reinstall Debian for my computer, my family computers and friends computers, I have to install some pacakages.
Being so many packages and doing it all over again so many times on so many computers, it started to become a chore so I created a small bash script to automate the installation of all required packages.
But unfortunately this works only if the packages are in Debian's repository.
I didn't have time to extend it to work also with just local .deb files.

So that's one of main reason I want more of the packages in Debian's repository itself.

Anyway, I understand that this is not a good moment for that.

Many thanks anyway for the reply!

**Comment by ReenigneArcher** [comment]
> Anyway, what should be the other command?

`wget`/`curl` to download the file

e.g. `wget https://github.com/LizardByte/Sunshine/releases/latest/download/{file_name}`

**Comment by Danny3** [comment]
> > Anyway, what should be the other command?
> 
> `wget`/`curl` to download the file
> 
> e.g. `wget https://github.com/LizardByte/Sunshine/releases/latest/download/{file_name}`

I normally download the .deb files with the web browser and just install them from the command line, but that's cool to have too!

Thanks!

**Comment by Danny3** [comment]
> > On the other hand, I don't know how often is that the upstream is also the maintainer of the Debian package, but (as of today,) I'd like to focus on developing the app.
> 
> Basically, I agree with this sentiment. We make the packages available for everyone on GitHub, and they can be installed with 2 simple commands.
> 
> Also, there's no way I'm advocating for putting this into Debian until the project is much more stable and reliable. At this point we don't even have unit testing.

Does the project have unit testing now?
