### ISSUE TITLE
Can't quit session

### ISSUE THREAD

**Issue by magalhas** [LizardByte/Sunshine#1709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Trying to quit a previous existing session through Moonlight (on Android) results in the following error: "Host PC returned error: All sessions must be disconnected before quitting (Error code: 503)".

I'm using the same device that I've used to connect before, couple of days ago. I'm currently on vacations so I'm locked out of the PC this way.

### Expected Behavior

Previous session to terminate allowing new connections.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.20

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce 3090

### GPU Driver/Mesa Version

Can't tell now

### Config

```Shell
No access to it as of now but it's close to the default one.
```

### Relevant log output

```shell
Can't access now.
```

**Comment by magalhas** [comment]
Resuming the session also does not work throwing concurrent session limit error.

**Comment by distrohelena** [comment]
Just commenting here re-opens it?

Helloo, sorry for barging in but I had this issue happen to me yesterday, and with MonitorSwapAutomation installed this means I cannot close a session, which does not return my main display on.

This is hard to reproduce as it happened randomly, but my Steam Deck OLED got an error right after RDP handshake, and didnt open the session. Subsequent sessions worked fine, but because there was 1 lost session the MonitorSwap scripts would not execute, resulting in my Desktop PC being locked.

I had to connect back, and manually go to the MonitorSwapTool and re-load my primary monitor config (could have also just changed on Windows Settings). 

This is not impossible to solve, while also being really annoying to reproduce.

My only possible data is that I have 2 routers sharing the same SSID, Wi-Fi 6. This happened when I moved my Steam Deck from my bedroom to my office and tried connecting to my desktop PC again. 

My desktop is wired to the wall (entire house is CAT6 to the main router, secondary router is APed and connected to the wall).

Thanks for any help! If this happens again I'll try collecting as much data as possible.

**Comment by in-jun** [comment]
Same issue here. The stuck session blocks everything until you restart Sunshine.

I wrote a small watchdog as a workaround — it tails the log, detects the disconnect, and calls `POST /api/apps/close`. Sunshine stays up, dead session is gone.

https://github.com/in-jun/sunshine-session-fix
