### ISSUE TITLE
PC reboots without prompt

### ISSUE THREAD

**Issue by mortenmoulder** [LizardByte/Sunshine#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Installed on Windows - PC immediately started rebooting after install.

### Expected Behavior

Expected a "reboot now", "reboot later", etc. buttons.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

latest

### Package

Windows - installer

### GPU Type

n/a

### GPU Model

N/A

### GPU Driver/Mesa Version

N/A

### Config

```Shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by ReenigneArcher** [comment]
The restart is caused by a bug in an old version of ViGEmBus. https://github.com/LizardByte/Sunshine/discussions/1718#discussioncomment-7326308

I have no idea what version is the cause, but it must be older than [1.21.442](https://github.com/nefarius/ViGEmBus/releases/tag/v1.21.442.0) released August 30, 2022, as that is the only version Sunshine has ever installed.
