### ISSUE TITLE
Windows uninstaller does not remove Start Menu shortcut

### ISSUE THREAD

**Issue by sitiom** [LizardByte/Sunshine#200]
### Describe the Bug

The start menu shortcut does not get removed on uninstallation of Sunshine:
![image](https://user-images.githubusercontent.com/56180050/173987004-fe7a3790-2287-4c93-b4fc-853d57200ace.png)
![image](https://user-images.githubusercontent.com/56180050/173987020-46aed624-f0b9-49b4-9c51-6d0342fc7a19.png)

### Expected Behavior

It should get removed on uninstallation.

### Sunshine Host Operating System and Version

Windows 11

### Architecture

64 bit

### Sunshine Version

0.14.0

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070 SUPER

### GPU Driver/Mesa Version

512.95

**Comment by ReenigneArcher** [comment]
This is a note for myself:

Adding `CPACK_NSIS_DELETE_ICONS_EXTRA` "should" resolve this.

https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_DELETE_ICONS_EXTRA

Should probably also use [CPACK_NSIS_CREATE_ICONS_EXTRA](https://cmake.org/cmake/help/latest/cpack_gen/nsis.html#variable:CPACK_NSIS_CREATE_ICONS_EXTRA) instead of `CPACK_NSIS_CREATE_ICONS` here:
https://github.com/SunshineStream/Sunshine/blob/master/CMakeLists.txt#L496

Reference for adding multiple entries to start menu and desktop: https://stackoverflow.com/questions/2640760/creating-windows-desktop-icon-in-cmake-cpack-nsis
