### ISSUE TITLE
No Audio on host when audio output bitrate is anything other than 48000hz

### ISSUE THREAD

**Issue by ssesik** [LizardByte/Sunshine#233]
### Describe the Bug

No audio on host when audio device is set to output any bitrate other than 48khz.

### Expected Behavior

Audio works across different bitrates. (maybe detect and downsample bitrate?)

### Additional Context

only tested with Play audio on PC option enabled in moonlight client.

### Sunshine Host Operating System and Version

Windows 10

### Architecture

64bit x86

### Sunshine Version

0.14.0

### GPU Type

AMD

### GPU Model

RX 470

### GPU Driver/Mesa Version

22.5.1

**Comment by lateforwork1000** [comment]
I’m getting no sound even after changing from 48khz I have a rx 5500 running windows 11

**Comment by RussellAult** [comment]
Just ran into this exact problem. If the chosen audio_sink (system default or otherwise) is set to have a Default Format of 44.1 kHz (and probably others) Sunshine will not pass audio and prints the messages ``Error: Couldn't find supported format for audio`` and ``Error: Couldn't create audio input``. Changing the Default Format of the device to 48 kHz allows audio to work and makes the messages disappear.
