### ISSUE TITLE
[Win] Service not starting if temp is on another drive

### ISSUE THREAD

**Issue by reloxx13** [LizardByte/Sunshine#2391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

As mentioned in https://github.com/LizardByte/Sunshine/issues/1791 , the service does not start if the temp folder is moved to another drive.
In my case its on Z:\temp as a RAMDisk.

Maybe an issue with 
https://github.com/LizardByte/Sunshine/blob/116e59292af3a76e3d816f147da620e416968115/tools/sunshinesvc.cpp#L128

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

0.23.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

0

### GPU Driver/Mesa Version

0

### Config

```Shell
min_log_level = 3
global_prep_cmd = [{"do":"cmd /C \"C:\\Program Files\\Sunshine\\tools\\QRes.exe\" /x:%SUNSHINE_CLIENT_WIDTH% /y:%SUNSHINE_CLIENT_HEIGHT% /r:%SUNSHINE_CLIENT_FPS%","undo":"cmd /C \"C:\\Program Files\\Sunshine\\tools\\QRes.exe\" /x:1920 /y:1080 /r:60","elevated":false}]
native_pen_touch = disabled
upnp = enabled
port = 48989
channels = 2
min_threads = 4
```

### Relevant log output
From windows event log
```shell
Der Dienst "SunshineService" wurde mit folgendem Fehler beendet: 
Das System kann den angegebenen Pfad nicht finden.
```

**Comment by psyke83** [comment]
Hi,

Can you share the contents of these environment variables from a command line?

```
echo %TMP%
echo %TEMP%
```

`GetTempPathW()` uses the first path it finds in the above order (and the user temp profile `%USERPROFILE%`, but we don't need to see it).

If `TMP` is referencing the wrong path, that's your problem.

**Comment by reloxx13** [comment]
```
C:\>echo %TEMP%
Z:\Temp

C:\>echo %TMP%
Z:\Temp

C:\>echo %USERPROFILE%
C:\Users\xxx
C:\>
```

**Comment by ReenigneArcher** [comment]
Can services interact with other drives by default? From my experience they cannot without adjustments.

Maybe this will help? https://docs.lizardbyte.dev/projects/sunshine/en/latest/troubleshooting/windows.html#permission-denied

**Comment by reloxx13** [comment]
Do you think any other service would run for over 4 years or more since i use the ramdisk on a full media and gaming server?

**Comment by cgutman** [comment]
I suspect the problem here is that only your user account has that Z: volume mounted. System and services accounts like LocalSystem, LocalService, and NetworkService run under separate profiles with separate mounted volumes (local disks will generally mount system-wide but other type of disks will not necessarily do that). You can confirm this is the problem by using PsExec to run a command prompt in the LocalSystem account like `PsExec.exe -s -i cmd.exe` and then trying to `dir Z:\`.

Overriding your system wide TMP and TEMP variables to point to an inaccessible volume is a broken configuration and will cause any services running under those accounts to fail to write temporary files. Your override has also probably created a privilege escalation vulnerability on your system since the regular `%SYSTEMROOT%\Temp` directory contains very specific ACLs to prevent DLL planting vulnerabilities which are necessary because both privileged and unprivileged applications are able to write to the system-wide temp directory.

What you can do instead is make your TMP/TEMP variable overrides in the user-specific environment variable configuration rather than system-wide. That should resolve all those issues.

**Comment by reloxx13** [comment]
The screenshot shows another service starting the same as sunshine and can write log files on z, same as other services for multiple years now, the Z:\Temp folder is full of temp files from working services. ONLY sunshine is crashing. It also shows the Z:\Temp dir as LocalSystem.     

     
![grafik](https://github.com/LizardByte/Sunshine/assets/14855001/f152c492-0f8f-4215-aac6-6b66d53e9c5c)
     
Without a proper error message, we dont even know if it is the log file problem or if it just cannot find the sunshine.exe cause of not escaped paths etc. But the log file isnt created in z:\temp when starting as service.    

Should the log file be in Z:\temp dir if i start sunshine.exe manual? it is next to the sunshine.conf.

**Comment by cgutman** [comment]
> Should the log file be in Z:\temp dir if i start sunshine.exe manual? it is next to the sunshine.conf.

There's 2 log files normally. One from Sunshine.exe itself that is placed next to sunshine.conf (containing just the log output of the single Sunshine.exe process) and the other is from SunshineSvc.exe that is normally in `%SYSTEMROOT%\Temp` (containing the output of _all_ Sunshine.exe processes that have been run since the service started).

> Without a proper error message, we dont even know if it is the log file problem or if it just cannot find the sunshine.exe cause of not escaped paths etc. But the log file isnt created in z:\temp when starting as service.

I don't know what you expect us to do in this case. How are we supposed to report an error message without a log file? Services cannot interact with the user desktop due to Session 0 Service Isolation, so displaying an error dialog is impossible.

We propagate the Win32 error code to the Service Control Manager when we fail to start, so you may find it in your Windows Event Log in an error from Service Control Manager reporting a service start failure. If that doesn't provide a definitive cause, I suggest using ProcMon to see the exact NTSTATUS code of the failing file operation.

> The Temp ACLs should move with the new TEMP ENV directory, else a attack could just change the temp dir and than plant dll´s.
Windows is designed to change the TEMP dir.

No, changing the system-wide temp directory requires administrator rights, so it does not provide an EoP possibility (attacker must already be admin to do that).

Based on the fact that you have Z:\Temp open in Explorer, the ACLs _didn't_ go with the Temp directory, because Explorer (which runs with a restricted token) is not able to enumerate files in C:\Windows\Temp normally. The standard ACLs on C:\Windows\Temp trigger Explorer to request elevation, and after elevation the ACLs are _permanently_ modified to allow your user full access to the directory (note: this permanent modification may mean that it _looks_ like the regular Temp ACLs are not in place, but it's just because you accidentally modified them some time earlier by accessing the directory with Explorer).

**Comment by reloxx13** [comment]
Besides that, something is still wrong in getting a correct path and this is a bug.    

Great that everything works besides sunshine and you are going to ignore it 👎🏻

**Comment by ReenigneArcher** [comment]
Sunshine is a do-ocracy. If you want something, do it.

**Comment by cgutman** [comment]
@reloxx13 I made some suggestions in my prior post of things for you to run to get more information, but as I mentioned this isn't actionable without understanding more details about the exact operation that's failing.

If I had to psychic debug this, I'd guess that maybe your Temp directory doesn't exist at the time that SunshineSvc.exe starts.
