### ISSUE TITLE
How can I get client's information? or whether the client connected or not?

### ISSUE THREAD

**Issue by Kobain-Seo** [LizardByte/Sunshine#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I took a look codes and there is page for clients.( server.resource["^/clients/?$"]["GET"] = getClientsPage;)

But it is empty page. Is there any way to get client's information or check client is connected?

### Host Operating System

Windows

### Operating System Version

Windows 10 20H

### Architecture

64 bit

### Sunshine commit or version

0.22

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

497.29

### Config

```Shell
Not relevant.
```

### Relevant log output

```shell
Not relevant.
```

**Comment by ReenigneArcher** [comment]
That endpoint would return `clients.html` if it existed. It was probably a placeholder that never got completed.

You can parse the logs I guess... there's no other way to determine the connected clients right now.

**Comment by sambuev** [comment]
Woudl be great to see some info, such as SMPT settings and email notifications.

**Comment by Hazer** [comment]
@sambuev There's https://github.com/LizardByte/Sunshine/pull/2042 that will allow to see paired devices and unpair, is that what you're looking for? 

If you want more information, there's currently nothing planned.

**Comment by evertonstz** [comment]
I'm gonna necrobump this issue because I think I found a way to partially do this. 

I use [Artemis 2](https://github.com/Artemis-RGB/Artemis) to manage my RGB and my initial idea was to develop a plugin to disable my PC rgb when Sunshine is connected to it. Looking around for a way to determine if there's a cliente connected to Sunshine I found this Issue and it seems there's no official way.

My workaround was to use windows' environment variables and sunshine's command preparations: on connect I run `setx SUNSHINE_CONNECTED "true"` and on disconnect I run `setx SUNSHINE_CONNECTED "false"`.

I wrote my artemis plugin to detect changes on this env var and voila :)
