### ISSUE TITLE
16:10 green Bar on right side

### ISSUE THREAD

**Issue by skunk-funk** [LizardByte/Sunshine#2636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [ ] I have read the documentation

### Is your issue present in the latest beta/pre-release?

- [ ] This issue is present in the latest pre-release

### Describe the Bug

When streaming a 16:10 host to a 16:10 client, sunshine does not send the full screen and puts a thick green Bar about the right-hand side of the client. Have tried at various resolutions and various clients and several sunshine versions. 

### Host Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Architecture

32 bit

### Sunshine commit or version

23

### Package

Linux - deb

### GPU Type

AMD

### GPU Model

Rx 580

### GPU Driver/Mesa Version

whatever's in 22.04

### Capture Method (Linux Only)

pipewire

### Config

```Shell
output_name = 0
channels = 5
adapter_name = /dev/dri/renderD128
```

### Relevant log output

```shell
None
```

**Comment by phamaralbr** [comment]
![Screenshot_20240604_181729_Moonlight](https://github.com/LizardByte/Sunshine/assets/70783034/e6d8731c-967d-4b8e-9dd6-da11ce4e8825)

I have the same problem. Seems like it's a problem with ffmpeg. An easy workaround for now would be using H264 instead of HVEC.

**Comment by skunk-funk** [comment]
Should this be an issue in ffmpeg instead?

I don't have the chops to translate this to that world.

**Comment by gschintgen** [comment]
Thanks for reporting the issue. I don't think the architecture is 32-bit and I highly doubt the capture method is the (unreleased) pipewire capture method. Logs are always appreciated even if nothing is "relevant" in an obvious way.

That being said it's a known issue with AMD cards: The h265 encoder works in blocks of 64x16 pixels. This clashes with Apple's vendor-specific resolutions (other resolutions may also be affected). Unfortunately those non-aligned resolutions aren't handled correctly by mesa / ffmpeg. There's a [comment on stackexchange](https://unix.stackexchange.com/a/775217) detailing what needs to be done (in general) to get this fixed:

1. On the mesa / radeonsi / libva side of things the API is been enhanced to provide a means so that drivers can inform other layers of the stack of the pixel alignment required by the hardware. Apparently this should be ok with recent mesa versions.
2. On the ffmpeg side these alignment values must be retrieved and handled correctly.

Sunshine uses its own ffmpeg build as a build dependency. This ffmpeg is built (on purpose, for compatibility reasons) against a rather old libva version. Consequently the [ffmpeg patch](https://ffmpeg.org/pipermail/ffmpeg-devel/2024-March/323941.html) that is available can't work correctly. But we have [confirmation ](https://discord.com/channels/804382334370578482/1246074499234009148/1246616380242001940) that hardcoding the required alignment values in sunshine's ffmpeg copy does indeed fix the issue (if the rest of the host system is recent enough).

One possible solution might be to modify the ffmpeg patch so that it does not try to retrieve the correct alignment values from libva but to "simply"(?) check if the GPU vendor is AMD and use the 64 by 16 alignment in that case. (It would probably still require up-to-date libva/mesa on the host system, since other alignment/padding related changes have also been made.)

An alternative could be to investigate the possibility of using a patched ffmpeg in the AppImage since that build is more self-contained and uses an up-to-date libva.

PRs are welcome :-)

**Comment by gschintgen** [comment]
Note also that on the screenshot there is not only a green bar to the right but also a small black bar at the bottom. Probably 8 pixels to make it a multiple of 16.

I recently streamed h265 to an older 1600x900 laptop (software decoding) and there was also a small black bar at the bottom and the image was a bit blurry since moonlight scaled it down to fit the screen. (Must have been 912 rows instead of 900.)

It may be this issue on ffmpeg's bug tracker: 
https://trac.ffmpeg.org/ticket/8506
We should probably build the latest ffmpeg from source and report the findings upstream if it's still reproducible from the CLI.

It's peculiar though that I can't seem to remember moonlight ever reporting 1088 for FullHD in its overlay, but for the 1600x900 case it did indeed report a larger row number.
(More testing needed, as always...)

**Comment by matte-schwartz** [comment]
> Note also that on the screenshot there is not only a green bar to the right but also a small black bar at the bottom. Probably 8 pixels to make it a multiple of 16.
> 
> I recently streamed h265 to an older 1600x900 laptop (software decoding) and there was also a small black bar at the bottom and the image was a bit blurry since moonlight scaled it down to fit the screen. (Must have been 912 rows instead of 900.)
> 
> It may be this issue on ffmpeg's bug tracker: https://trac.ffmpeg.org/ticket/8506 We should probably build the latest ffmpeg from source and report the findings upstream if it's still reproducible from the CLI.

So my findings when working off of that bug report ticket are as follows:

Without the patch, my results match up perfectly with the original issue and misaligned video sizes.

With this patch: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240321170219.1487-1-Primeadvice@gmail.com/  applied on top release/6.1 (it doesn't apply cleanly to ffmpeg-git anymore), my output video size is the proper 1920x1080 using the exact same commands as before the patch so it no longer matches the issue report. The size is also accurate for 1600x900 and 3440x1440 videos.

May take me a bit to figure out how to test this within Sunshine so we can know for sure whether the patch does or does not work.

I was not aware of this thread before filing this Mesa bug, but I've kept it open for now since that's the best way I've found around this issue on my own 7900xtx setup: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11491

**Comment by cordlord** [comment]
> ![Screenshot_20240604_181729_Moonlight](https://private-user-images.githubusercontent.com/70783034/337280573-e6d8731c-967d-4b8e-9dd6-da11ce4e8825.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDc3MjEsIm5iZiI6MTcyMjM0NzQyMSwicGF0aCI6Ii83MDc4MzAzNC8zMzcyODA1NzMtZTZkODczMWMtOTY3ZC00YjhlLTlkZDYtZGExMWNlNGU4ODI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEzNTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzNmZmY5YTQ5OTYyMmRlMmMzODUzZjBkN2Y1MWM2Y2MzMmVlYjU2NzBkMTI0YWU4ZTUyNjgwZmMwZDk5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDjJFJ1xt8KX3fLh9Rbohyps2WqoPIbzTT_yNo1Q62s)
> 
> I have the same problem. Seems like it's a problem with ffmpeg. An easy workaround for now would be using H264 instead of HVEC.

Just to chime in as I had this issue today, disabling HVEC support fixed this immediately for me on version 0.23.1.

I'm running Ubuntu 24.04, with kernel 6.8
CPU is AMD Ryzen 7 5700U (16) @ 4.37 GHz
GPU is AMD Lucienne [Integrated]

**Comment by phamaralbr** [comment]
Seems like a fix was merged but unfortunately the issue still persists for me.

As you can see there is still a green bar on the right side of the screen while using HEVC:

![Screenshot_20241005_145639_Moonlight](https://github.com/user-attachments/assets/7c05b474-89b7-47f3-bc6b-d8bc2a319ace)

I'm on the latest sunshine: Version v2024.1005.14704

**Comment by matte-schwartz** [comment]
The fix technically *does* work, but because of the way build-deps get created in the CI, it uses libraries that are too out-of-date when building ffmpeg for Sunshine specifically. Should hopefully be fixed if/when the way build-deps get compiled changes.

**Comment by phamaralbr** [comment]
Would it be too difficult to apply this patch ourselves until this is fixed?

**Comment by ReenigneArcher** [comment]
This should be merged soonish https://github.com/LizardByte/Sunshine/pull/3263

**Comment by matte-schwartz** [comment]
@ReenigneArcher is the runner also getting changed with this? otherwise I'm worried it'll have the exact same issue. I remember when making my .spec package, I had to recompile the build-deps individually on my own Fedora system and then put them in that tarball to use during the build rather than the CI artifacts because Ubuntu LTS did not ship one/multiple libraries in the build-deps runner.

**Comment by ReenigneArcher** [comment]
Oh... I understand your statement now. The runner did not change. We're building on ubuntu 22.04 for now.

**Comment by cgutman** [comment]
Don't we actually need to set `log2_alignment` on our side for the FFmpeg patch to have any effect?

**Comment by matte-schwartz** [comment]
I had a fully working build without patching sunshine and just using the rebuilt build-deps with the existing patches.
```
[2024:07:12:18:23:01]: Debug: [hevc_vaapi @ 0x34dc09c0] Using customized alignment size [64x16].
```
https://discord.com/channels/804382334370578482/1246074499234009148/1261493805522354196

**Comment by cgutman** [comment]
Ah yes, I missed that hwcontext_vaapi sets it.

**Comment by cgutman** [comment]
@matte-schwartz Can you try with the build-deps from this run? https://github.com/LizardByte/build-deps/actions/runs/11209095043?pr=363

**Comment by matte-schwartz** [comment]
@cgutman 
looks good on my end with that run, just dropped the Linux-x86_64 folder into place of the included one and re-compiled on Arch, no green line is present and logging looks good. 
```
2024-10-06 23:21:34.214]: Info: vaapi vendor: Mesa Gallium driver 24.3.0-devel for AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.59, 6.12.0-rc1-5-cachyos-rc-lto-test)
[2024-10-06 23:21:34.214]: Debug: [AVHWDeviceContext @ 0x7552e0b5b0c0] VAAPI driver: Mesa Gallium driver 24.3.0-devel for AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.8, DRM 3.59, 6.12.0-rc1-5-cachyos-rc-lto-test).
[2024-10-06 23:21:34.214]: Debug: [AVHWDeviceContext @ 0x7552e0b5b0c0] Driver not found in known nonstandard list, using standard behaviour.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Input surface format is p010le.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using VAAPI profile VAProfileHEVCMain10 (18).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using VAAPI render target format YUV420_10 (0x100).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using CTU size 64x64, min CB size 8x8.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] RC mode: CBR.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Block Level bitrate control: OFF.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] RC target: 100% of 30988000 bps over 8 ms.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] RC buffer: 258233 bits, initial fullness 193674 bits.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] RC framerate: 120/1 (120.00 fps).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Driver does not report any additional prediction constraints.
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using intra and P-frames (supported references: 1 / 0).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] All wanted packed headers available (wanted 0xd, found 0x1f).
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using customized alignment size [64x16].
[2024-10-06 23:21:34.214]: Debug: [hevc_vaapi @ 0x7552e0baeec0] Using level 5.1.
```

![IMG_2185](https://github.com/user-attachments/assets/5f2f7cbd-eefc-4d7e-a17d-9b389a9d8aab)

some additional validation from others would be good just in case

**Comment by ReenigneArcher** [comment]
@gschintgen see https://discord.com/channels/804382334370578482/1313221611381325844

**Comment by HateJoysticks** [comment]
I'm still having the same issue...

**Comment by Khaivn1308** [comment]
Im still having this issue. Green lines on the right and the bottom of the screen 
Using sunshine.AppImage because of Ubuntu 25.10 having newer libs

<img width="2316" height="1080" alt="Image" src="https://github.com/user-attachments/assets/5f0b67dd-72df-472e-9cad-29a8e4d8ae8f" />

**Comment by ReenigneArcher** [comment]
@Khaivn1308 try the beta appimage
