### ISSUE TITLE
Request for Sunshine DEB Package for Ubuntu 18.04

### ISSUE THREAD

**Issue by JoeAndMark** [LizardByte/Sunshine#2853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Dear Sunshine Developers,

I hope this message finds you well.

First and foremost, thank you for creating and maintaining such an excellent tool. I am currently using an industrial PC with Ubuntu 18.04 for work purposes and would like to set up remote desktop access using Sunshine in combination with Moonlight.

However, after spending an entire day trying to compile Sunshine from source using a Docker container with Ubuntu 18.04, according to the reference [Sunshine](https://docs.lizardbyte.dev/projects/sunshine/en/v0.14.0/building/linux.html), I have not been successful. Therefore, I am reaching out to kindly request if anyone could provide a precompiled DEB package for Ubuntu 18.04.

Your assistance would be greatly appreciated, as it would save me a considerable amount of time and effort. Thank you very much in advance for your help.

Best regards.

### Host Operating System

Linux

### Operating System Version

Ubuntu 18.04

### Architecture

32 bit

### Sunshine commit or version

I have no idea.

### Package

Linux - deb

### GPU Type

Intel

### GPU Model

I have no idea.

### GPU Driver/Mesa Version

I have no idea.

### Capture Method

None

### Config

```Shell
I have no idea.
```

### Relevant log output

```shell
I have no idea.
```

**Comment by ReenigneArcher** [comment]
Thank you for your interest in Sunshine, but we won't be providing packages for EOL OSes, and you really should consider upgrading to a newer version for security purposes.

There is a ubuntu 18.04 dockerfile that was removed in this commit: https://github.com/LizardByte/Sunshine/commit/77deff12a668b2db6499eb0accb8f9b14139f891#diff-4a5832d35e54c17f9c2bc89801edba0329e609488acf3d7f65664df80655650b

I could never get it to work, which is why it was named as "todo". I forget what exactly was failing to build back then.

I can say you will need to compile cmake yourself, use newer gcc/g++ versions than is provided in Ubuntu 18.04 out of the box, and probably some hacks for ffmpeg (our ffmpeg submodule is no longer compatible with anything older than Ubuntu 22.04).

**Comment by JoeAndMark** [comment]
> Thank you for your interest in Sunshine, but we won't be providing packages for EOL OSes, and you really should consider upgrading to a newer version for security purposes.
> 
> There is a ubuntu 18.04 dockerfile that was removed in this commit: [77deff1#diff-4a5832d35e54c17f9c2bc89801edba0329e609488acf3d7f65664df80655650b](https://github.com/LizardByte/Sunshine/commit/77deff12a668b2db6499eb0accb8f9b14139f891#diff-4a5832d35e54c17f9c2bc89801edba0329e609488acf3d7f65664df80655650b)
> 
> I could never get it to work, which is why it was named as "todo". I forget what exactly was failing to build back then.
> 
> I can say you will need to compile cmake yourself, use newer gcc/g++ versions than is provided in Ubuntu 18.04 out of the box, and probably some hacks for ffmpeg (our ffmpeg submodule is no longer compatible with anything older than Ubuntu 22.04).

Thank you for your reply. 
I understand what you mean, and I will try new ways to use remote desktop or report it to my leader.
All in all, thank you again for creating such a great tool.
Best regards.
