### ISSUE TITLE
After connecting, the screen is black but the mouse can be controlled

### ISSUE THREAD

**Issue by a13997020** [LizardByte/Sunshine#312]
### Describe the Bug

After connecting, the screen is black but the mouse can be controlled

### Sunshine Host Operating System and Version

win11  21h2   

### Architecture

64

### Sunshine Version

0.14.0

### GPU Type

amd

### GPU Model

6600xt

### GPU Driver/Mesa Version

22.7.1

**Comment by ReenigneArcher** [comment]
Provide more context.

**Comment by carlthome** [comment]
Same issue here on Ubuntu 22.04. What context do you need @ReenigneArcher?

**Comment by ReenigneArcher** [comment]
Steps required to reproduce the issue.

**Comment by Milor123** [comment]
I have this same problem, I am trying connect my laptop to my windows 10 (VMware), The game works very nice, the problem is that I set the FULLSCREEN mode and the laptop with moonlight, then do blackscreen and only can see the mouse, but in my host the game is good, and cant use BORDERLESS because i get drop fps (its a vmware problem)

Notes:
- My host resolution is exactly the same of the my guest (Verified using tools\dxgi-info.exe)
- I've add the new resolution in sunshine using the GUI platform
- I've tried change the resolution on moonlight, to Native, to 720P, try change FPS, and other options but always get the same result.
