### ISSUE TITLE
Fedora Aarch64 RPM

### ISSUE THREAD

**Issue by gbraad** [LizardByte/Sunshine#3354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

For Debian there is an Arm64/Aarch64 release, but not for Fedora.

### Expected Behavior

A package that can be installed as an RPM on an Aarch64 machine, like an Ampere Altra, or similar.

### Additional Context

https://github.com/LizardByte/Sunshine/releases/tag/v0.23.1

- Shows Fedora 39, and 40 (AMD64)

### Host Operating System

Linux

### Operating System Version

Fedora 40+

### Architecture

arm64/aarch64

### Sunshine commit or version

n/a

### Package

Linux - Fedora Copr

### GPU Type

n/a

### GPU Model

n/a

### GPU Driver/Mesa Version

n/a

### Capture Method

None

### Relevant log output

```shell
n/a
```

**Comment by gbraad** [comment]
I see:
https://github.com/LizardByte/Sunshine/blob/f418566b3123eca4a426e5c57bf8bf7d9293a3db/packaging/linux/fedora/Sunshine.spec#L142C1-L144C5
mentions aarch64, so testbuilds most likely have been made? Is there a COPR instance set up for this?

**Comment by ReenigneArcher** [comment]
Search for LizardByte or Sunshine on copr.

**Comment by gbraad** [comment]
Found these on COPR:
- https://copr.fedorainfracloud.org/coprs/lizardbyte/stable/
- https://copr.fedorainfracloud.org/coprs/lizardbyte/beta/
These do not follow the naming convention as expected, so others named `sunshine` seem to be preferred by others: https://copr.fedorainfracloud.org/coprs/ericthomasca/sunshine/

**Comment by gbraad** [comment]
I appreciate @ReenigneArcher to close the issue, but this does not work as expected.
As you can see in:
https://download.copr.fedorainfracloud.org/results/lizardbyte/stable/fedora-40-x86_64/08120769-copr-ci/
and in:
https://download.copr.fedorainfracloud.org/results/lizardbyte/stable/fedora-40-aarch64/08120769-copr-ci/

there is no package named: `Sunshine`

This means the instructions on: https://docs.lizardbyte.dev/projects/sunshine/en/master/md_docs_2getting__started.html#fedora

are in error. At the moment this only works as follows ?

```
$ sudo dnf copr enable lizardbyte/stable
$ sudo dnf install copr-ci
```

and that is NOT the expected package that works to install Sunshine.

![image](https://github.com/user-attachments/assets/3699b319-74d5-4a0d-bd25-48c70d6b0f05)

It would be appreciate to provide working packages in the releases on GitHub instead.

**Comment by ReenigneArcher** [comment]
You have to use beta until the next stable release.

Also these are package repositories. There's no guarantee or expectation that each copr repo contains only one package. Since more than Sunshine will live there in the future this is the structure we opted for.

We are not providing fedora packages on GitHub releases going forward. Copr is the preferred method for most users.

**Comment by gbraad** [comment]
Thanks. Tested with the beta and this works. Looking forward to the stable version 👍 

> Copr is the preferred method for most users.

Understandable

**Comment by Arcitec** [comment]
> We are not providing fedora packages on GitHub releases going forward. Copr is the preferred method for most users.

I think it's brilliant that you have set up a COPR repo for the nightly release. That's super convenient. :) Thanks a lot!

It seems like this ticket is the only place that mentioned it though. I found this ticket because I searched for "Fedora" in all tickets. There's currently no mention in the docs, may be good to list it here under Linux:

https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/setup.html#install
