### ISSUE TITLE
Can't start on Debian 10 | GLIBC_2.30 not found | GLIBCXX_3.4.26 not found

### ISSUE THREAD

**Issue by LeChatNoir666** [LizardByte/Sunshine#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

OS: Debian 10 / Raspbian x86

I've downloaded the sunshine.deb and installed it as in your instructions.

If I want to start Sunshine I get the following errors:
```
sunshine: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by sunshine)
sunshine: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by sunshine)

```
But somehow I can't update the "libc6" to that version because:
```
apt-cache policy libc6
libc6:
  Installiert:           2.28-10+deb10u2
  Installationskandidat: 2.28-10+deb10u2
  Versionstabelle:
 *** 2.28-10+deb10u2 500
        500 http://security.debian.org buster/updates/main i386 Packages
        100 /var/lib/dpkg/status
     2.28-10+deb10u1 500
        500 http://ftp.debian.org/debian buster/main i386 Packages
```

I've also followed this instructions to install the appimage with:
./sunshine.AppImage --appimage-extract
Starting it with ./AppRun gives me:
`/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
`
What can I do now?

Many thanks in advance.

### Expected Behavior

Sunshine starts

### Host Operating System

Linux

### Operating System Version

Raspbian x86 (For Desktops) based on Debian 10

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### GPU Type

none (software encoding)

### GPU Model

Integrated Intel

### GPU Driver/Mesa Version

How can I find out?

Btw: Are there other keyboard shortcuts than CTRL+Shift+Alt+Q?
Like to minimize the Window?
I've checked the dokumentation but can't find something...

**Comment by KuleRucket** [comment]
From https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
Ctrl+Alt+Shift+Q - Quit the streaming session (leaving the game running on the host PC)
Ctrl+Alt+Shift+Z - Toggle mouse and keyboard capture
Ctrl+Alt+Shift+X - Toggle between full-screen and windowed mode
Ctrl+Alt+Shift+S - Open performance stats overlay (not supported on Steam Link or Raspberry Pi)
Ctrl+Alt+Shift+M - Toggle mouse mode (pointer capture or direct control)
Ctrl+Alt+Shift+V - Type clipboard text on the host
Ctrl+Alt+Shift+D - Minimize the stream window
Ctrl+Alt+Shift+C - Toggle local cursor display in remote desktop mouse mode (remote cursor will always show up due to GameStream limitations)
Ctrl+Alt+Shift+L - Toggle locking the mouse pointer to the video area (requires "Optimize mouse for remote desktop instead of games" checkbox enabled)

**Comment by Tim-Paik** [comment]
I think recompiling from source will fix this
