### ISSUE TITLE
Bitrate overshoot (H264, H265 10 bit)

### ISSUE THREAD

**Issue by Isalight** [LizardByte/Sunshine#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When using H264 and H265 10bit codecs, the bitrate exceeds the set value. When using H265 8 bits there are no problems.
For example, the bitrate (moonlight) is 20 Mbps. Real bitrate: H265 ~ 20 Mbps, H265 10bit ~ 25 Mbps, H264 ~ 27 Mbps.
Or bitrate (moonlight) is 30 Mbps. Real bitrate: H265 ~ 28 Mbps, H265 10bit ~ 35 Mbps, H264 ~ 39 Mbps.

### Expected Behavior

The bitrate of all codecs must match within the set.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

64 bit

### Sunshine commit or version

0.17.0

### Package

Windows - portable

### GPU Type

Nvidia

### GPU Model

RTX 3060 Ti

### GPU Driver/Mesa Version

527.37

**Comment by cgutman** [comment]
This is actually the expected behavior (though it's not necessarily intuitive). When you set the "video bitrate" option in Moonlight, you really are _just_ changing the video encoder bitrate.

There is additional bandwidth consumed during a stream by things other than the encoded video stream. There is a (by default) an additional 20% FEC parity data added, then there's audio data alongside that.

The reason you're seeing the stream seem to obey the video bitrate limit when using HEVC is because HEVC actually uses a lower bitrate than what's selected in Moonlight (75% of the selected bitrate). The reason was an attempt to balance the image quality and bandwidth savings of HEVC over H.264 to get a some of both benefits. HEVC Main 10 doesn't engage this bitrate reduction behavior, so that's why it behaves like H.264.

Moonlight clients further have additional logic to behave more strictly when it comes to bitrate when streaming remotely. The thinking there is that a user might configure Moonlight to 5 Mbps because they really only have 5 Mbps of upload or download bandwidth, so we don't want to exceed that. For remote streams, Moonlight will subtract the 20% from the selected bitrate to account for FEC (and subtract a little more to account for audio and control data), so it will really try not to exceed the specified limit (even though it's not supposed to be anything other than the video encoder bitrate).

**Comment by Isalight** [comment]
Thanks for the detailed explanation! Most of the time I use streaming over the Internet. But lately, the quality of the provider's connection (from the side of the host machine) has been unstable, so I was looking for the optimal bitrate and noticed the difference between the codecs.
