### ISSUE TITLE
Incorrect keys sometimes passed from Moonlight to Sunshine

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/Sunshine#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Using Moonlight Android as a client and attempting to type with the on screen keyboard will sometimes result in incorrect key presses being sent.

For example, attempting to use the capital letter "Y" will sent a lowercase "y". No capital letters are ever sent and always result in the lowercase version.

Attempting to hold the "m" button to obtain a "?" will result in a "/" character being typed on the host. Sending a "?" directly from the dedicated "?" button will also result in a "/".

### Additional Context

These are the incorrect symbols, anything not listed is correct or doesn't send anything.

| Android | Host |
| ------- | ---- |
| @ | 2 |
| # | 3 |
| $ | 4 |
| _ | - |
| & | 7 |
| + | = |
| ( | 9 |
| ) | 0 |
| * | 8 |
| " | ' |
| : | ; |
| ! | 1 |
| ? | / |
| ~ | ` |
| ^ | 6 |
| { | [ |
| } | ] |
| % | 5 |
| < | , |
| > | . |

Additionally a `|` character results in `\`.

Symbols that don't appear on a normal keyboard, such as Pi, do not send anything (this could be due to my testing which was in Notepad).

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

v0.18.3

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2080 Super

### GPU Driver/Mesa Version

528.49

**Comment by cgutman** [comment]
This a combination of Moonlight Android issues and Sunshine issues.

The issues with capitals and symbols being entered without Shift pressed is a bug in Sunshine. It should be generating a synthetic Shift keypress if a key event comes in with the Shift modifier flag set but Shift is not already down (same with other modifiers). The Shift key is handled very strangely with most software keyboards on Android (it behaves as a toggle key, like Caps Lock), which is why it doesn't appear on other platforms or with a hardware keyboard.

The issue with special characters like Pi not working was an issue in Moonlight Android that I fixed in https://github.com/moonlight-stream/moonlight-android/commit/370dbb1a10a65a500a88608235e4055601229390

**Comment by cgutman** [comment]
Fixed by 44f89de33b2263d456f40fbd483fbe659fa4023b
