### ISSUE TITLE
Cannot connect after disconnecting from RDP session

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/Sunshine#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

With Sunshine running as a service, cannot connect to Sunshine from Moonlight after using the Windows built in method of disconnecting from a remote desktop session.

Can connect if using this workaround, but that leaves the system unlocked, so is not preferred. This is a batch script that must be run as admin. It is not a prep command for Sunshine.
```batch
@echo off
for /f "skip=1 tokens=3" %%s in ('query user %USERNAME%') do (
  %windir%\System32\tscon.exe %%s /dest:console
)
```

Can also connect to locked desktop as before using RDP.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

v0.18.3

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2080 Super

### GPU Driver/Mesa Version

528.49

**Comment by da-anda** [comment]
this is not specific to sunshine. This also is/was the case with nvidia GameStream. It's even mentioned in the Moonlight troubleshooting section that using RDP will cause this issue.

**Comment by digi-chris** [comment]
Not sure if this helps find a solution, but I have the same issue and I've found that when it happens, I can fix it by logging in using VNC. After logging in that way, it seems to clear the problem and Moonlight will work again.

I've written some test code just to figure out what's going on with RDP. I find that occasionally when logged in with RDP, if I enumerate the available monitors on the machine, I'll get a list of the actual physical displays as presented by the GPU. Generally everything works fine when this is the case. However most of the time I'll get a list of 'virtual' displays, and this seems to be when things go wrong.

Whenever the displays listed are virtual, I'll then find Moonlight won't log in when I quit the RDP session. My theory is that Windows gets locked in a state where it's 'detached' from the physical monitors, and then Sunshine can't hook into the GPU because there's no output on it.

Going to the actual machine and logging in puts things back as they were before, and now Sunshine works because the GPU is once again displaying the desktop. Likewise, logging in with VNC seems to act in the same way as being at the physical machine - so it fixes the problem.

It's just a theory but I think if somebody figured out what VNC server is doing (I'm using TigerVNC for my tests) during that initial connection, it might present a solution for Sunlight?

**Comment by ReenigneArcher** [comment]
Logging back in with any method fixes it, even RDP if you disconnect with the script I put above.

**Comment by ReenigneArcher** [comment]
> the script did not work for me at all

It's a batch script, you need to run it as admin while connected to the remote desktop session. This is not a prep command script for Sunshine.

**Comment by svenlange2** [comment]
I have found that if you "start -> log out" instead of just close the RDP connection from the "x", then youll be able to log back with Moonlight. Next time the Moonlight connection opens (I am using the Desktop connection) you'll be presented with login screen of Windows.

**Comment by xx1182** [comment]
> I have found that if you "start -> log out" instead of just close the RDP connection from the "x", then youll be able to log back with Moonlight. Next time the Moonlight connection opens (I am using the Desktop connection) you'll be presented with login screen of Windows.

This doesn't work for me, tried both clicking my username and the "shutdown icon" to disconnect. The script works.

**Comment by ReenigneArcher** [comment]
> could execute this command or perhaps a better scoped version of that calls the very same API that the tscon.exe tool does to close out any open rdp sessions

This would be a security risk if an attacker had access to a paired moonlight client... kicking out an admin connected to RDP. RDP should take priority over any moonlight session.

Let's be real... far too many users are giving moonlight access to casual friends and family members. So we won't automatically handle this for you, but feel free to add it as a prep command (that may work).

**Comment by Nonary** [comment]
> > could execute this command or perhaps a better scoped version of that calls the very same API that the tscon.exe tool does to close out any open rdp sessions
> 
> 
> 
> This would be a security risk if an attacker had access to a paired moonlight client... kicking out an admin connected to RDP. RDP should take priority over any moonlight session.
> 
> 
> 
> Let's be real... far too many users are giving moonlight access to casual friends and family members. So we won't automatically handle this for you, but feel free to add it as a prep command (that may work).

Prep commands won't work because they require an active console session now, which RDP closes out when disconnecting.

**Comment by Nonary** [comment]
I would say it's pretty unlikely we would add a workaround to this problem. By design, windows won't allow us to execute processes under a users account unless they're an "active" console session.

The reason why sunshine doesn't work is because of this limitation. If you execute an application that has no command and prep commands disabled, it will let you in without issues.

By leaving the command/detached field blank and make sure it has no prep commands (including global ones) it will not matter that a user is not signed in or disconnected, you will be able to tunnel in and sign in without issues.

**Comment by cgutman** [comment]
The original bug reported here is fixed by 9955890023e4f855231d1690555c7ffda7264cdf. Sunshine will respawn on the console session when the original session is taken over by RDP. Logging back into an existing connection will result in a disconnection as Sunshine spawns back into the new console session, but otherwise is usable now.

We can't do prep/undo commands for the reasons mentioned above.

**Comment by stammerjoker** [comment]
I still have this problem with Sunshine 0.21.0. It should have been fixed in v0.20.0. Anybody else?

**Comment by ReenigneArcher** [comment]
Works for me... You still need to disconnect the rdp session.

**Comment by phuein** [comment]
> I still have this problem with Sunshine 0.21.0. It should have been fixed in v0.20.0. Anybody else?

I found a setting in Sunshine -> Applications that might be related:

> Continue streaming if the application exits quickly

I'm using Desktop, so will try unchecking this option.

**Comment by diphuaji** [comment]
This script saved my day! You just need to store the code in a file ending with `.bat` and right click -> run as admin. Done

**Comment by Nonary** [comment]
> This script saved my day! You just need to store the code in a file ending with `.bat` and right click -> run as admin. Done

You don't need a script as long as you've installed the latest version of Sunshine.

And you need to launch the Desktop app in Moonlight, to sign back in, otherwise it will fail until you sign back in

**Comment by diphuaji** [comment]
> > This script saved my day! You just need to store the code in a file ending with `.bat` and right click -> run as admin. Done
> 
> You don't need a script as long as you've installed the latest version of Sunshine.
> 
> And you need to launch the Desktop app in Moonlight, to sign back in, otherwise it will fail until you sign back in

I am using the latest version I downloaded 3 days ago and I HAVE to use the script, or else I can't even launch the Desktop app in Moonlight (from Mac).

**Comment by ReenigneArcher** [comment]
> I am using the latest version I downloaded 3 days ago and I HAVE to use the script, or else I can't even launch the Desktop app in Moonlight (from Mac).

You should just be able to disconnect from your RDP session, and then connect using Moonlight. I don't believe you need the bat script I posted anymore, as long as you disconnect yourself. You can disconnect via "start/power/disconnect".

**Comment by DavidReddecliffe** [comment]
I still have this issue using the latest prerelease version of Sunshine
